
Sound.create(filename: "/sounds/Academy_All.mp3", luminence: 2, color: 3)
Sound.create(filename: "/sounds/Acoustic_Guitar_1_CMa_100.mp3", luminence: 5, color: 5)
Sound.create(filename: "/sounds/Acoustic_Guitar_1_CMa_100.mp3", luminence: 5, color: 6)
Sound.create(filename: "/sounds/ambient1.mp3", luminence: 3, color: 7)
Sound.create(filename: "/sounds/ambient2.mp3", luminence: 3, color: 8)
Sound.create(filename: "/sounds/Bass_1_CMa_100.mp3", luminence: 1, color: 3)
Sound.create(filename: "/sounds/Academy_All.mp3", luminence: 2, color: 3)
Sound.create(filename: "/sounds/Academy_All.mp3", luminence: 2, color: 3)
Sound.create(filename: "/sounds/Borealis_CMa_100.mp3", luminence: 6, color: 2)
Sound.create(filename: "/sounds/Delicate_Piano_1_CMa_100.mp3", luminence: 6, color: 4)
# Sound.create(filename: "/sounds/Piano_CMa_100.mp3", luminence: 6)
Sound.create(filename: "/sounds/Strings_6_CMa_100.mp3", luminence: 2, color: 7)
